### ISSUE TITLE
support bool data type

### ISSUE THREAD

**Issue by databasedav** [aerospike/aerospike-client-rust#125]
aerospike added a specific bool data type in 5.6 https://docs.aerospike.com/server/guide/data-types/scalar-data-types#boolean, after writing a bool with this data type in the python client https://aerospike-python-client.readthedocs.io/en/latest/aerospike.html#aerospike.AS_BOOL, reading from the record on the rust client panics, this addition is super convenient because otherwise we need to read the bools as ints on the rust client

**Comment by khaf** [comment]
Coming next release.

**Comment by khaf** [comment]
Took a while for the "next release", but it is released and includes this feature.

**Comment by databasedav** [comment]
@khaf thanks, can u also merge those those changes into the `async` branch?

**Comment by khaf** [comment]
I did, but hit an error that wasn't immediately clear how to fix, and I had other pressing issues. Back on it now.

**Comment by khaf** [comment]
Pushed.
