### ISSUE TITLE
FloatValue enum uses u32 and u64 types instead of f32 and f64

### ISSUE THREAD

**Issue by a-rodin** [aerospike/aerospike-client-rust#54]
Hi!

I'm trying to use `FloatValue` and it looks weird that it has `u32` and `u64` in the enum declaration instead of `f32` and `f64` correspondingly:

https://github.com/aerospike/aerospike-client-rust/blob/430780ae408a1e224b9ad3a232db36d61099ad3a/src/value.rs#L35-L42

So in order to use for example `f32` value it is necessary to invoke [`mem::transmute_copy::<u32, f32>`](https://doc.rust-lang.org/std/mem/fn.transmute_copy.html).

**Comment by jhecking** [comment]
Sorry for the late response.

`FloatValue` implements `From<f32>` so you can just call `FloatValue::from(f32)` to get a `FloatValue` from an `f32`.

If you just want to convert your `f32` into a `Value` object, you can also use the `as_val!` macro.
