### ISSUE TITLE
Looking for documentation to setup aerospike cluster

### ISSUE THREAD

**Issue by probtask** [aerospike/aerospike-client-rust#66]
I am trying to `cargo test` but reached error after setting up `vagrant up` https://www.aerospike.com/docs/operations/install/vagrant/mac

I verified I can `ssh` into `vagrant` and insert element and that `127.0.0.1 3000` is able to be `telnet` 

Error:

```
test node_names ... FAILED
test nodes ... FAILED
test get_node ... FAILED

failures:

---- node_names stdout ----
thread 'node_names' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Connection("Failed to connect to host(s). The network connection(s) to cluster nodes may have timed out, or the cluster may be in a state of flux."), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', tests/common/mod.rs:43:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- nodes stdout ----
thread 'nodes' panicked at 'Once instance has previously been poisoned', src/libstd/sync/once.rs:395:21

---- get_node stdout ----
thread 'get_node' panicked at 'Once instance has previously been poisoned', src/libstd/sync/once.rs:395:21


failures:
    get_node
    node_names
    nodes

test result: FAILED. 1 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--test client'

```

Can someone point me a direction for minimum steps to run `cargo test`? Is there local cluster install instruction lying somewhere?

**Comment by jhecking** [comment]
Docker is probably one of the easiest ways to quickly spin up a dev cluster, e.g. check out this blog post from on of our engineers: https://dev.to/aerospike/how-do-i-get-a-2-nodes-aerospike-cluster-running-quickly-in-docker-without-editing-a-single-file-2bnj

Once you have the cluster up and running, just make sure you set the `AEROSPIKE_HOSTS` environment variable to your clusters endpoint(s).

**Comment by probtask** [comment]
Awesome, thanks for the link, the test worked after using docker to spawn up cluster.
