### ISSUE TITLE
Support Predicate Filtering

### ISSUE THREAD

**Issue by jonas32** [aerospike/aerospike-client-rust#70]
Hello,

i just started to implement the Rust Client into one of my Services.
While doing that, i found out that it is not supporting [Predicate Filtering](https://www.aerospike.com/docs/guide/predicate.html) filtering. It would be great if this Client would also support it. 
Querying for multiple secondary bins is really hacky without this.

Thanks
Jonas

**Comment by jhecking** [comment]
Hi @jonas32, yes, that would be great! Honestly speaking, the fastest way to get that feature added would be to submit a pull request, if possible? I could provide guidance and feedback, but do not have the time myself to take this on end-to-end at the moment.

**Comment by jonas32** [comment]
Hey @jhecking, i can try to implement it. I also dont have much time to do it. It might take some time and probably your guidance will be needed.

**Comment by khaf** [comment]
Since time is at a premium for all involved, I'd caution against this for a few months, since the current predicate expressions are going to be deprecated on the server side and a new API will be released in the new few months.
All efforts on this issue until then will be wasted effort.

**Comment by jonas32** [comment]
At some point it would be wasted, but on the other hand, its an important feature. For me, this library is nearly useless without it for example. I would have to use the C lib with Rust bindings. 
Im not sure if i could even finish the old API before the new API is released, but im sure the old one wont be removed for legacy reasons. And supporting both cant be bad.

**Comment by khaf** [comment]
Per the current plan, the old API *will* be removed, both from the server and the clients.

**Comment by jonas32** [comment]
Ah ok. That changes it.
I guess the new API is not yet documented?
Do you have any infos on how long we have to wait until the release of the new one?

**Comment by khaf** [comment]
No dates, but in near future. The old APIs will be supported on the server for a short while, but there will be a clean cut on the newer releases of the clients.

**Comment by rbotzer** [comment]
Hi @jonas32. When the new predicate filter is in place (targeted for version 5.2) the server will still support the current API. It will be deprecated, but not removed until a later version. This gives you many months to use the current API, if you implement it.  Your PR would be appreciated.

**Comment by jonas32** [comment]
Thank you for this Information @rbotzer. 
I will try to implement it and open a PR as soon as it works.
