### ISSUE TITLE
Feature Request: Rust UDF

### ISSUE THREAD

**Issue by Bajix** [aerospike/aerospike-client-rust#77]
It would be great to be able to write native modules similar to how this can be done with Redis. Is that on the road map?

**Comment by rbotzer** [comment]
We're working hard on adding data types with a native API of operations, such as the recently added [bitwise operations](https://www.aerospike.com/docs/guide/bitwise.html) on the bytes data type and [HLL/HMH](https://www.aerospike.com/docs/guide/hyperloglog.html) ones. You can already compose these into transactions using operate() and predicate filters. It's always better to _not_ use UDFs when you can get what you need from native Aerospike API operations - they perform and scale better than a Lua UDF.

We're also in progress on another native operations front, but I don't want to spoil the fun.

Regarding UDFs, overhauling those are on the roadmap, and Rust is always an interesting option. Your feature request is noted!

In general, [The Aerospike Standup](https://www.aerospike.com/category/blog/aerospike-standup/) blog is a great way to keep track of all the new developer features. You can subscribe to it and get a quick overview of what's new.
