### ISSUE TITLE
CDT Operations for List, Map and Bitwise

### ISSUE THREAD

**Issue by jonas32** [aerospike/aerospike-client-rust#78]
Hello,

currently the client only supports a limited set of operations for the custom data types and bitwise.
Is there a specific reasons only the few currently are supported or was there just no time to implement the others like list remove by value?
Im probably going to implement them, but i was curious why some are supported and some are not. 
Also the list cdt seems to be not fully implemented (return types etc)

**Comment by jhecking** [comment]
Hi Jonas, the Aerospike Server has added new CDT operations at various points over the last couple of years. The Rust client only implements CDT operations that were available as of ~ Oct 2017.

**Comment by jonas32** [comment]
Hey Jan, i already guessed this might be the reason. Good to know. Ill start implementing the other ones.
Are there any operations other than the missing ones from list/map and bitwise completely that are missing currently?

**Comment by jhecking** [comment]
In terms of new operations, AS 4.9 introduced a completely new set of operations on the [HyperLogLog (HLL) probabilistic data type](https://www.aerospike.com/docs/guide/hyperloglog.html). Also 4.7 added a new delete operation to enable atomic read-then-delete.

There were also several enhancements to the existing list/map CDT operations, which the Rust client is missing:
* Support for optional element creation in nested CDT operations – also introduced in 4.9.
* Support for operating on lists and maps nested within lists and maps using [CDT Subcontext evaluation](https://www.aerospike.com/docs/guide/cdt-context.html) was added in 4.6.
* [`INF` and `WILDCARD` types](https://www.aerospike.com/docs/guide/cdt-ordering.html) for map and list comparators were added in 4.3.1.
* Relative range operations for CDTs, and `NO_FAIL` and `DO_PARTIAL` CDT error policies, which were added in 4.3.0.

And I may have missed some other, minor things... Quite a bit of functionality that's missing from the Rust client. Really appreciate your contributions! It's really good to see more interest in the Aerospike Rust client lately.

Also, it may make sense to break down the changes into multiple PRs, e.g. by data type (list/map/bitmap) or some other criteria that makes sense to you. That would make the review process a lot easier.

**Comment by jonas32** [comment]
Yes definitely.
I already found the missing HLL compared to the Java client. The current functionality is really limited. The whole implementation differs strongly from for example Go or Java right now. Ill try to get the basic implementation of operations to work and create the first PR. Probably ill rewrite the existing part completely. That might be easier and faster than comparing line to line with Go and Java.

**Comment by rbotzer** [comment]
Hi @jonas32. I'm looking into this right now, I'll get back to you as soon as I can.

**Comment by jonas32** [comment]
@jhecking i guess this issue is resolved then too. I will open a new one for HLL later.

**Comment by jhecking** [comment]
Yes, it is. Thank you again!
