### ISSUE TITLE
Support for batchRead or batchGet

### ISSUE THREAD

**Issue by abhilashg1** [aerospike/aerospike-client-rust#88]
I don't see the support for batchRead or batchGet in the [https://www.aerospike.com/apidocs/rust/aerospike/index.html?search=batch](url). Either the docs are not updated or something is off, we cannot map one to one correlation with github codes and API docs.

**Comment by jonas32** [comment]
The docs are updated, but its a little tricky to find. Here you go:
https://docs.rs/aerospike/0.6.0/aerospike/struct.Client.html#method.batch_get
For a better implementation example, check this: 
https://github.com/aerospike/aerospike-client-rust/blob/master/tests/src/batch.rs

But as i said, its a little tricky. Maybe we should try to improve the docs.

**Comment by jhecking** [comment]
The docs at https://docs.rs/aerospike/ are the most up-to-date. Those API docs are also linked from https://www.aerospike.com/docs/client/rust/. I'm not sure when or how the docs at www.aerospike/apidocs/rust were generated, but they are very out of date. I will try to replace them with a reference to the docs at docs.rs instead.

**Comment by jhecking** [comment]
> I will try to replace them with a reference to the docs at docs.rs instead.

This is done. www.aerospike.com/apidocs/rust/ now redirects to the docs at docs.rs instead.

@abhilashg1 I'm going to close this issue. Feel free to re-open or file another issue if you still have problems getting batch commands to work.
