### ISSUE TITLE
HLL Datatype and Operations

### ISSUE THREAD

**Issue by jonas32** [aerospike/aerospike-client-rust#89]
The Client should feature HLL Operations and Expressions for a 1.0 Release.
The PR for HLL is already finished. It just misses the Tests (same as the FilterExpressions PR).
I will merge request this as soon as the other one is merged.
By the way, the Documentation of HyperLogLog seems broken: https://www.aerospike.com/docs/guides/hyperloglog
It only shows 404 and the Links to the HyperLogLog Page also dont work.

Please assign me.

**Comment by rbotzer** [comment]
Thanks for pointing that out. We'll get on fixing the link in the docs.

**Comment by kportertx** [comment]
Correct link: https://www.aerospike.com/docs/guide/hyperloglog/
